[package]
name = "net_me_tube_server_runtime"
version = "0.1.0"
authors = ["Kieran McKenzie <sporious@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
